### ISSUE TITLE
Check if value is in enum.

### ISSUE THREAD

**Issue by thomasfosterau** [rwaldron/enum-definitions#4]
This may be a silly question (I have little experience with enums in general, although I'm pretty sure I understand the concept) - but what would be the best way to check if a value is a part of an enum? 

For example:

``` javascript
enum Colors {
  RED,
  BLUE,
  GREEN,
  YELLOW
}

const myCar = new Car({color: Colors.RED});

myCar.color // Colors.RED

/**
 * What would be the best way to check that myCar.color is one of the enumerators of Colors?
 * Would overloading instanceof make sense, as shown below? Object.values()?
 */

Colors[Symbol.hasInstance] = function(lhs){
  return Object.values(this).filter(value => value === lhs).length > 0;
}

myCar.color instanceof Colors // true
```

**Comment by jeffmo** [comment]
As the spec is written currently, you should be able to do:

``` js
Colors.hasOwnProperty(myCar.color)
```

**Comment by rwaldron** [comment]
As mentioned https://github.com/rwaldron/proposal-enum-definitions/issues/1#issuecomment-239871358 ... Presently, everything in this repo is out of date, so please don't bother commenting on it. We've been working on a way to provide a mechanism that allows the values to be user-code definable, with intuitive defaults. Thanks
